export const pricingList = [
  {
    title: "Messari Basic",
    plan: "Free",
    desc: "Free Plan for All Users",
    list: [
      "Daily crypto news & insights newsletter",
      "Basic watchlist sreener & features",
      "Free research reports",
      "Basic quarterly reports",
    ],
    buttonText: "Get Started Now",
  },
  {
    title: "Messari Pro",
    plan: "$75.00/month",
    desc: "Our most popular plan",
    list: [
      "Daily crypto news & insights newsletter",
      "Basic watchlist sreener & features",
      "Free research reports",
      "Basic quarterly reports",
      "Daily crypto news & insights newsletter",
      "Basic watchlist sreener & features",
      "Free research reports",
      "Basic quarterly reports",
    ],
    buttonText: "Start Your Free 2-day Trial",
    recommended: true,
  },
  {
    title: "Messari Enterprise",
    plan: "Custom",
    desc: "Best for businesses",
    list: [
      "Daily crypto news & insights newsletter",
      "Basic watchlist sreener & features",
      "Free research reports",
      "Basic quarterly reports",
      "Daily crypto news & insights newsletter",
      "Basic watchlist sreener & features",
      "Free research reports",
      "Basic quarterly reports",
      "Basic quarterly reports",
      "Daily crypto news & insights newsletter",
      "Basic watchlist sreener & features",
      "Free research reports",
      "Basic quarterly reports",
    ],
    buttonText: "Start Your Free 2-day Trial",
  },
];
